#ifndef GLOBALSHARED_H
#define GLOBALSHARED_H

typedef enum {NO_CONNECTIONS_RESPONSE, NO_LOCATIONS_RESPONSE, NO_SCHEDULEITEMS_RESPONSE, XML_PARSING_ERROR, XML_ERROR_RESPONSE,HTML_PARSING_ERROR, HTML_ERROR_RESPONSE,NOTYPE_ERROR, NO_LOCATIONS, NO_CONNECTIONS, NO_SCHEDULE, AOK} eStatusID;
typedef enum {B,F} eTimeType;
#endif // GLOBALSHARED_H
